import React from 'react';
import Statspage from './Status';
export const metadata = {
  title: "Stats Page",
  description: "Generated by create next app",
}

const Statsokpage = () => {
    return (
        <div>
            <Statspage/>
        </div>
    );
};

export default Statsokpage;