export const metadata = {
  title: "TimeLine Page",
  description: "Generated by create next app",
};

import React from 'react';
import Timelinepage from '../../component/Client';

const page = () => {
  return (
    <div>
      <Timelinepage/>
    </div>
  );
};

export default page;