import Friends from "@/component/FriendsCord/Friends";
import Herosection from "@/component/Herosection/Hero";

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

const Homepage = async () => {
  const res = await fetch("http://localhost:3000/friends.json", {
    cache: "no-store",
  });

  const friend = await res.json();

  return (
    <div className="bg-base-200 w-full">
      <div className="w-[85%] mx-auto">
        <Herosection friend={friend} />

        <h1 className="text-xl font-bold">Your Friends</h1>

        <div className="mt-5 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          {friend.map((item) => (
            <Friends key={item.id} item={item} />
          ))}
        </div>
      </div>
    </div>
  );
};

export default Homepage;